# Generated by Django 6.0.1 on 2026-01-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='batch_records/', verbose_name='Arquivo PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Lote')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Documento')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Texto Extraído (Raw)')),
            ],
            options={
                'verbose_name': 'Registro de Lote',
                'verbose_name_plural': 'Registros de Lote',
            },
        ),
    ]
