# Generated by Django 6.0.1 on 2026-01-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrecord',
            name='issue_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Issued Date'),
        ),
        migrations.AddField(
            model_name='batchrecord',
            name='project_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='batchrecord',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='batchrecord',
            name='document_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Document No'),
        ),
    ]
